### PR TITLE
Added  Chinese | 添加简体中文的支持 

### PR DESCRIPTION
**Pull request by 1976222027**
Added support for Simplified Chinese   
 添加简体中文的支持

### CODE REVIEW

**Comment by 1976222027** [comment]
添加简体中文的支持 
Added support for Simplified Chinese

**Comment by Danesprite** [comment]
Hello Mahongyin,

I thank you for your translation of the *TTS Util* resource strings.  It
was unexpected and much appreciated; I know there are a few Chinese users
of my application.

I should tell you that, since I (most regretfully) cannot read any Chinese,
I am quite unable to judge whether your translation captures the semantics
accurately.  Translation is a tricky thing, after all.  We will see how it
goes.

Were you thinking of adding translations for strings in the arrays.xml and
plurals.xml files under app/src/main/res/values?  A partial translation is
fine by me, of course, especially since you've done this for free.

I will mention in the README file, in the changelog and in the
application's About screen that the Chinese translation is by you.

**Comment by 1976222027** [comment]
Dear Danesprite，
I have finished correcting Chinese mistakes, and almost anyone who knows Chinese can understand it

**Comment by Danesprite** [comment]
Dear Mahongyin,

Very good.  Thanks again.  I will now add the attribution notices mentioned
above.

I thank you also for the Chinese version of the README.  You should know,
however, that parts of it will soon become out-of-date, since I will
be updating the English text to reflect the changes in the next version of
*TTS Util* (4.0.0).

**Comment by Danesprite** [comment]
Dear Mahongyin,

I have added the attribution notices and merged the most recent changes
into this branch, including the changes to the README file mentioned above.
There are six additional string resources.  Although translating them is
not essential -- you have already done plenty! -- it will make this
translation complete.

About the only thing left to do after this pull request is merged is to
create screenshots of the application in Chinese.  This I will do.

The sample text used in the English screenshots comes from a public domain
work -- Adam Smith's /The Wealth of Nations/.  The first Chinese text that
came to mind was Sun Tzu's /The Art of War/.  The (traditional) Chinese text
of this work is, obviously, in the public domain and is available online, so
I'll use that.

Thanks again,
Dane

**Pull request merged**
